on:
  push:

name: Testing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test
      - name: Run Backend tests
        run: |
          newman run ./src/backend_tests.json